name: Datadog Reporter
description: Collects detailed stats on build times and outcomes and sends to datadog
author: https://github.com/better
requirements:
  - docker
configuration:
  properties:
    dogstatsd_host:
      type: string
    dogstatsd_port:
      type: string
    metric_prefix:
      type: string
    additional_tags:
      type: array
      minimum: 1
      items:
        type: object
        properties:
          tag:
            type: string
          env_var:
            type: string
          value:
            type: string
  required:
    - dogstatsd_host
  additionalProperties: false
