#!/bin/bash

set -euo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

# shellcheck source=lib/get-tags.sh
. "$basedir/lib/get-tags.sh"
# shellcheck source=lib/report-to-datadog.sh
. "$basedir/lib/report-to-datadog.sh"
# shellcheck source=lib/time-diff.sh
. "$basedir/lib/time-diff.sh"
# shellcheck source=lib/get-metric-name.sh
. "$basedir/lib/get-metric-name.sh"

NOW=$(date +%s%3N)

echo "--- :datadog: Recording step run time"

METRIC_NAME=$(getMetricName "step.duration")
METRIC_VALUE=$(timeDiff "$BUILDKITE_PLUGIN_DATADOG_STATS_STEP_START_TIME_MS")
TAGS=$(getTags)

reportToDatadog "${METRIC_NAME}" "${METRIC_VALUE}" h "${TAGS}"
STEP_SUCCEEDED=$([[ $BUILDKITE_COMMAND_EXIT_STATUS == 0 ]] && echo "true" || echo "false")
reportToDatadog "custom.ads.buildkite.step" "1" d "${TAGS},success:${STEP_SUCCEEDED},build:${BUILDKITE_BUILD_URL}"
